# Generated by Django 5.1.1 on 2024-10-20 20:55

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='LocalFotos',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('local', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='Fotos',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('legenda', models.CharField(max_length=200)),
                ('imagem', models.ImageField(upload_to='web/')),
                (
                    'local',
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to='web.localfotos',
                    ),
                ),
            ],
        ),
    ]
