# Generated by Django 5.1.1 on 2024-10-20 21:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0002_localfotos_fotos'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fotos',
            name='legenda',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
